# Server Port
server.port=8082

# Application Name
spring.application.name=physiobook-receptionist

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username =${DATASOURCE_USERNAME}
spring.datasource.password = ${DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Kafka Consumer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=receptionist-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-serializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Topic Name
app.kafka.topic=doctor-events
app.kafka.topic.doctor=doctor-events
app.kafka.topic.appointment=appointment-events

app.kafka.topic.receptionist=receptionist-events
app.kafka.topic.patient=patient-events