# Server Port
server.port=8082

# Application Name
spring.application.name=physiobook-receptionist

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username =${DATASOURCE_USERNAME}
spring.datasource.password = ${DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.server.port=8082 