# Server Port
server.port=8082

# Application Name
spring.application.name=physiobook-receptionist

# PostgreSQL Database (AWS RDS)
spring.datasource.url=jdbc:postgresql://rec.cz4q2y8qi47t.eu-north-1.rds.amazonaws.com:5432/physiobook_receptionist
spring.datasource.username=admin_rec
spring.datasource.password=admin_rec
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.server.port=8082 